//model DemandeParticipation
export interface DemandeParticipation{
  id: string,
  nomPrenomDemandeur: string,
  directeurTheseDoctorant: string,
  gsm: string,
  email: string,
  fonction: "Chercheur" | "Enseignant chercheur",
  etablissement: string,
  nomLaboratoire: string,
  discipline: string,
  natureManifestation: "Congrès" | "Conférence" | "Séminaire" | "Colloque" | "Workshop" | "Stage",
  naturePriseEnCharge: "Frais de séjour" | "Billet d'avion",   
  intituleManifestation: string,
  paysManifestation: string,
  villeManifestation: string,
  dateManifestation: string,
  // Nouveaux champs pour les avis
  avisResponsableStructure: string,
  avisCommissionRechercheEtablissement: string,
  avisResponsableEtablissement: string,
  avisCommissionRechercheConseilUniversite: string,
  // Documents à fournir
  documentsFournis: {
    demandeOfficielle: File | null,
    lettreInvitation: File | null,
    programmeManifestation: File | null,
    resumeCommunication: File | null,
    formulaireMobilite: File | null,
    copieCarteEtudiant: File | null,
    rapportMission?: File | null // Pour les enseignants seulement
  },
  // Statut de la demande
  statut: "En attente" | "En cours d'évaluation" | "Approuvée" | "Rejetée",
  dateCreation: string,
  commentaireExpert?: string
}

//DATA liste demandes participations à manifestations non organisées à UH2C
export const listeDemandesParticipationsManifestations: DemandeParticipation[] = [
  {
    id: "1",
    nomPrenomDemandeur: "Elkanoun Mohamed",
    directeurTheseDoctorant: "",
    gsm: "+212 6 12 34 56 78",
    email: "elkanoun.mohamed@uh2c.ma",
    fonction: "Chercheur",
    etablissement: "Faculté des Sciences - Casablanca",
    nomLaboratoire: "Laboratoire de Mathématiques Appliquées",
    discipline: "Mathématiques",
    natureManifestation: "Conférence",
    naturePriseEnCharge: "Billet d'avion",
    intituleManifestation: "Conférence Internationale sur les Mathématiques Appliquées 2025",
    paysManifestation: "Centrafrique",
    villeManifestation: "Bangui",
    dateManifestation: "2025-11-05",
    avisResponsableStructure: "",
    avisCommissionRechercheEtablissement: "",
    avisResponsableEtablissement: "",
    avisCommissionRechercheConseilUniversite: "",
    documentsFournis: {
      demandeOfficielle: null,
      lettreInvitation: null,
      programmeManifestation: null,
      resumeCommunication: null,
      formulaireMobilite: null,
      copieCarteEtudiant: null
    },
    statut: "En attente",
    dateCreation: "2024-12-15"
  },
  {
    id: "2",
    nomPrenomDemandeur: "Dr. Ahmed Benali",
    directeurTheseDoctorant: "",
    gsm: "+212 6 98 76 54 32",
    email: "ahmed.benali@uh2c.ma",
    fonction: "Enseignant chercheur",
    etablissement: "École Nationale Supérieure d'Informatique",
    nomLaboratoire: "Laboratoire d'Intelligence Artificielle",
    discipline: "Informatique",
    natureManifestation: "Congrès",
    naturePriseEnCharge: "Frais de séjour",
    intituleManifestation: "Congrès International d'Intelligence Artificielle 2025",
    paysManifestation: "France",
    villeManifestation: "Paris",
    dateManifestation: "2025-03-15",
    avisResponsableStructure: "",
    avisCommissionRechercheEtablissement: "",
    avisResponsableEtablissement: "",
    avisCommissionRechercheConseilUniversite: "",
    documentsFournis: {
      demandeOfficielle: null,
      lettreInvitation: null,
      programmeManifestation: null,
      resumeCommunication: null,
      formulaireMobilite: null,
      copieCarteEtudiant: null
    },
    statut: "Approuvée",
    dateCreation: "2024-11-20"
  },
  {
    id: "3",
    nomPrenomDemandeur: "Pr. Fatima Zahra Alami",
    directeurTheseDoctorant: "",
    gsm: "+212 6 55 44 33 22",
    email: "fatima.alami@uh2c.ma",
    fonction: "Enseignant chercheur",
    etablissement: "Faculté des Sciences Juridiques",
    nomLaboratoire: "Laboratoire de Droit International",
    discipline: "Droit",
    natureManifestation: "Séminaire",
    naturePriseEnCharge: "Billet d'avion",
    intituleManifestation: "Séminaire International sur le Droit de la Mer",
    paysManifestation: "Espagne",
    villeManifestation: "Madrid",
    dateManifestation: "2025-04-22",
    avisResponsableStructure: "",
    avisCommissionRechercheEtablissement: "",
    avisResponsableEtablissement: "",
    avisCommissionRechercheConseilUniversite: "",
    documentsFournis: {
      demandeOfficielle: null,
      lettreInvitation: null,
      programmeManifestation: null,
      resumeCommunication: null,
      formulaireMobilite: null,
      copieCarteEtudiant: null
    },
    statut: "En cours d'évaluation",
    dateCreation: "2024-12-10"
  },
  {
    id: "4",
    nomPrenomDemandeur: "Dr. Youssef El Mansouri",
    directeurTheseDoctorant: "",
    gsm: "+212 6 77 88 99 00",
    email: "youssef.mansouri@uh2c.ma",
    fonction: "Chercheur",
    etablissement: "Faculté des Sciences et Techniques",
    nomLaboratoire: "Laboratoire de Chimie Organique",
    discipline: "Chimie",
    natureManifestation: "Workshop",
    naturePriseEnCharge: "Frais de séjour",
    intituleManifestation: "Workshop International sur la Chimie Verte",
    paysManifestation: "Allemagne",
    villeManifestation: "Berlin",
    dateManifestation: "2025-05-18",
    avisResponsableStructure: "",
    avisCommissionRechercheEtablissement: "",
    avisResponsableEtablissement: "",
    avisCommissionRechercheConseilUniversite: "",
    documentsFournis: {
      demandeOfficielle: null,
      lettreInvitation: null,
      programmeManifestation: null,
      resumeCommunication: null,
      formulaireMobilite: null,
      copieCarteEtudiant: null
    },
    statut: "Rejetée",
    dateCreation: "2024-10-05"
  }
];